parameters:
  big_elibre.rootDir: /mnt/hd/work/www/elibre_data/
  big_elibre.uploadDir: /mnt/hd/work/www/elibre_data/upload/
  history_manager.rotate_count: 30
    
    

services:
  history_manager:
    class: Big\ElibreBundle\Utils\HistoryManager
#    arguments: ["@doctrine.orm.entity_manager", ]
    calls: 
      - [ setDbm, ["@doctrine.orm.entity_manager"]]
      - [ setRotateCount, ["%history_manager.rotate_count%"]]
